name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - psutil
  - toolz
  - matplotlib
  - seaborn
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scipy
  - qiskit
  - jupyterlab
  - pip                    # Pip for additional dependencies
  - pip:
      - qiskit-aer         # Qiskit Aer for simulators
      - qiskit-ibmq-provider # IBM Q API package
